// Emoji library, categories, search, and reaction helpers for DevDrop

export const QUICK_REACTIONS = [
  '👍', '❤️', '🔥', '😂', '👏', '🎉', '🤩', '🚀', '😢', '🤔', '💩', '⚡'
];

export const EMOJI_CATEGORIES = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😄',
    emojis: [
      { emoji: '😀', name: 'grinning face', keywords: 'happy smile grin' },
      { emoji: '😃', name: 'grinning face with big eyes', keywords: 'happy smile joy' },
      { emoji: '😄', name: 'grinning face with smiling eyes', keywords: 'laugh smile happy' },
      { emoji: '😁', name: 'beaming face with smiling eyes', keywords: 'grin smile happy' },
      { emoji: '😆', name: 'grinning squinting face', keywords: 'laugh haha lol' },
      { emoji: '😅', name: 'grinning face with sweat', keywords: 'sweat relief phew' },
      { emoji: '🤣', name: 'rolling on the floor laughing', keywords: 'rofl haha lol laugh' },
      { emoji: '😂', name: 'face with tears of joy', keywords: 'cry laugh haha lol' },
      { emoji: '🙂', name: 'slightly smiling face', keywords: 'smile slight content' },
      { emoji: '🙃', name: 'upside-down face', keywords: 'silly sarcasm ironic' },
      { emoji: '😉', name: 'winking face', keywords: 'wink flirt joke' },
      { emoji: '😊', name: 'smiling face with smiling eyes', keywords: 'blush smile proud' },
      { emoji: '😇', name: 'smiling face with halo', keywords: 'angel innocent good' },
      { emoji: '🥰', name: 'smiling face with hearts', keywords: 'love crush adore cute' },
      { emoji: '😍', name: 'smiling face with heart-eyes', keywords: 'love heart adore wow' },
      { emoji: '🤩', name: 'star-struck', keywords: 'excited wow amazed star' },
      { emoji: '😘', name: 'face blowing a kiss', keywords: 'kiss love affection' },
      { emoji: '😗', name: 'kissing face', keywords: 'kiss whistle' },
      { emoji: '😋', name: 'face savoring food', keywords: 'yum delicious taste' },
      { emoji: '😛', name: 'face with tongue', keywords: 'tongue silly tease' },
      { emoji: '😜', name: 'winking face with tongue', keywords: 'wink tongue crazy joke' },
      { emoji: '🤪', name: 'zany face', keywords: 'crazy wacky wild' },
      { emoji: '😝', name: 'squinting face with tongue', keywords: 'playful tongue mischievous' },
      { emoji: '🤑', name: 'money-mouth face', keywords: 'money cash rich rich' },
      { emoji: '🤗', name: 'smiling face with open hands', keywords: 'hug welcome warm' },
      { emoji: '🤭', name: 'face with hand over mouth', keywords: 'oops giggle secret' },
      { emoji: '🤫', name: 'shushing face', keywords: 'quiet hush secret silence' },
      { emoji: '🤔', name: 'thinking face', keywords: 'think hmm ponder wonder' },
      { emoji: '🤐', name: 'zipper-mouth face', keywords: 'zip quiet silence secret' },
      { emoji: '🤨', name: 'face with raised eyebrow', keywords: 'skeptical suspicious distrust' },
      { emoji: '😐', name: 'neutral face', keywords: 'neutral meh straight' },
      { emoji: '😑', name: 'expressionless face', keywords: 'blank whatever speechless' },
      { emoji: '😶', name: 'face without mouth', keywords: 'silent speechless quiet' },
      { emoji: '😏', name: 'smirking face', keywords: 'smirk sly flirt smug' },
      { emoji: '😒', name: 'unamused face', keywords: 'bored annoyed unhappy' },
      { emoji: '🙄', name: 'face with rolling eyes', keywords: 'eyeroll whatever duh' },
      { emoji: '😬', name: 'grimacing face', keywords: 'grimace awkward cringe eek' },
      { emoji: '🤥', name: 'lying face', keywords: 'lie pinocchio fake' },
      { emoji: '😌', name: 'relieved face', keywords: 'relief calm peaceful' },
      { emoji: '😔', name: 'pensive face', keywords: 'sad thoughtful depressed' },
      { emoji: '😪', name: 'sleepy face', keywords: 'tired nap snooze' },
      { emoji: '🤤', name: 'drooling face', keywords: 'drool hungry crave' },
      { emoji: '😴', name: 'sleeping face', keywords: 'sleep zzz goodnight' },
      { emoji: '😷', name: 'face with medical mask', keywords: 'sick mask virus illness' },
      { emoji: '🤒', name: 'face with thermometer', keywords: 'sick fever ill' },
      { emoji: '🤕', name: 'face with head-bandage', keywords: 'hurt bandage injured' },
      { emoji: '🤢', name: 'nauseated face', keywords: 'disgust gross sick green' },
      { emoji: '🤮', name: 'face vomiting', keywords: 'puke vomit sick gross' },
      { emoji: '🤧', name: 'sneezing face', keywords: 'sneeze cold sick tissue' },
      { emoji: '🥵', name: 'hot face', keywords: 'heat warm sweat summer' },
      { emoji: '🥶', name: 'cold face', keywords: 'freezing ice winter cold' },
      { emoji: '🥴', name: 'woozy face', keywords: 'drunk dizzy intoxicated' },
      { emoji: '😵', name: 'face with crossed-out eyes', keywords: 'dizzy dead knocked out' },
      { emoji: '🤯', name: 'exploding head', keywords: 'mind blown shock amazed' },
      { emoji: '🤠', name: 'cowboy hat face', keywords: 'cowboy yeehaw western' },
      { emoji: '🥳', name: 'partying face', keywords: 'party celebrate birthday yay' },
      { emoji: '😎', name: 'smiling face with sunglasses', keywords: 'cool sunglasses chill boss' },
      { emoji: '🤓', name: 'nerd face', keywords: 'geek glasses smart study' },
      { emoji: '🧐', name: 'face with monocle', keywords: 'detective curious inspect classy' },
      { emoji: '😕', name: 'confused face', keywords: 'confused puzzled lost' },
      { emoji: '😟', name: 'worried face', keywords: 'worry concern nervous' },
      { emoji: '🙁', name: 'slightly frowning face', keywords: 'frown sad unhappy' },
      { emoji: '😮', name: 'face with open mouth', keywords: 'surprise wow shock gasp' },
      { emoji: '😯', name: 'hushed face', keywords: 'stunned quiet whoa' },
      { emoji: '😲', name: 'astonished face', keywords: 'shocked amazed astounded' },
      { emoji: '😳', name: 'flushed face', keywords: 'blush embarrassed red wide eyes' },
      { emoji: '🥺', name: 'pleading face', keywords: 'puppy eyes please beg cute' },
      { emoji: '😦', name: 'frowning face with open mouth', keywords: 'gasp shocked sad' },
      { emoji: '😧', name: 'anguished face', keywords: 'stunned pain agony' },
      { emoji: '😨', name: 'fearful face', keywords: 'scared fear terrified' },
      { emoji: '😰', name: 'anxious face with sweat', keywords: 'nervous panic sweat worry' },
      { emoji: '😥', name: 'sad but relieved face', keywords: 'close call phew relief' },
      { emoji: '😢', name: 'crying face', keywords: 'sad tear cry weep' },
      { emoji: '😭', name: 'loudly crying face', keywords: 'sob cry sobbing tear bawling' },
      { emoji: '😱', name: 'face screaming in fear', keywords: 'scream horror scared fear' },
      { emoji: '😖', name: 'confounded face', keywords: 'frustrated annoyed stressed' },
      { emoji: '😣', name: 'persevering face', keywords: 'struggle trying hard endure' },
      { emoji: '😞', name: 'disappointed face', keywords: 'letdown sad down' },
      { emoji: '😓', name: 'downcast face with sweat', keywords: 'tired stress hard work' },
      { emoji: '😩', name: 'weary face', keywords: 'tired exhausted frustrated' },
      { emoji: '😫', name: 'tired face', keywords: 'exhausted upset weary' },
      { emoji: '🥱', name: 'yawning face', keywords: 'bored sleepy yawn tired' },
      { emoji: '😤', name: 'face with steam from nose', keywords: 'triumph proud angry determined' },
      { emoji: '😡', name: 'enraged face', keywords: 'angry mad rage furious' },
      { emoji: '😠', name: 'angry face', keywords: 'mad annoyed upset' },
      { emoji: '🤬', name: 'face with symbols on mouth', keywords: 'swearing curse profanity mad' },
      { emoji: '😈', name: 'smiling face with horns', keywords: 'devil naughty evil cheeky' },
      { emoji: '👿', name: 'angry face with horns', keywords: 'devil demon evil wicked' },
      { emoji: '💀', name: 'skull', keywords: 'dead skeleton death dying laughing' },
      { emoji: '☠️', name: 'skull and crossbones', keywords: 'pirate poison danger toxic' },
      { emoji: '💩', name: 'pile of poo', keywords: 'poop crap poop joke funny' },
      { emoji: '🤡', name: 'clown face', keywords: 'clown circus funny silly' },
      { emoji: '👻', name: 'ghost', keywords: 'spooky halloween spirit boo' },
      { emoji: '👽', name: 'alien', keywords: 'ufo extraterrestrial sci-fi space' },
      { emoji: '🤖', name: 'robot', keywords: 'bot machine tech ai' },
      { emoji: '😺', name: 'grinning cat', keywords: 'cat kitty feline smile' },
      { emoji: '😸', name: 'grinning cat with smiling eyes', keywords: 'cat kitty haha' },
      { emoji: '😹', name: 'cat with tears of joy', keywords: 'cat cry laugh lol' },
      { emoji: '😻', name: 'smiling cat with heart-eyes', keywords: 'cat love heart cute' },
      { emoji: '😼', name: 'cat with wry smile', keywords: 'cat smirk sarcastic' },
      { emoji: '😽', name: 'kissing cat', keywords: 'cat kiss cute' },
      { emoji: '🙀', name: 'weary cat', keywords: 'cat scream scared shock' },
      { emoji: '😿', name: 'crying cat', keywords: 'cat sad tear cry' },
      { emoji: '🾾', name: 'pouting cat', keywords: 'cat angry mad' },
      { emoji: '💋', name: 'kiss mark', keywords: 'lips kiss lipstick love' },
      { emoji: '💌', name: 'love letter', keywords: 'heart mail envelope note' },
      { emoji: '💘', name: 'heart with arrow', keywords: 'cupid love romance' },
      { emoji: '💝', name: 'heart with ribbon', keywords: 'gift present love ribbon' },
      { emoji: '💖', name: 'sparkling heart', keywords: 'sparkle shiny love cute' },
      { emoji: '💗', name: 'growing heart', keywords: 'heartpulse affection love' },
      { emoji: '💓', name: 'beating heart', keywords: 'heartbeat pulse love' },
      { emoji: '💞', name: 'revolving hearts', keywords: 'two hearts love romance' },
      { emoji: '💕', name: 'two hearts', keywords: 'love pink hearts cute' },
      { emoji: '❣️', name: 'heart exclamation', keywords: 'exclamation punctuation love' },
      { emoji: '💔', name: 'broken heart', keywords: 'breakup heartbreak sad sorrow' },
      { emoji: '❤️', name: 'red heart', keywords: 'love red romance heart favorite' },
      { emoji: '🧡', name: 'orange heart', keywords: 'love orange warmth' },
      { emoji: '💛', name: 'yellow heart', keywords: 'love yellow friendship joy' },
      { emoji: '💚', name: 'green heart', keywords: 'love green nature health' },
      { emoji: '💙', name: 'blue heart', keywords: 'love blue peace loyalty' },
      { emoji: '💜', name: 'purple heart', keywords: 'love purple royalty magic' },
      { emoji: '🤎', name: 'brown heart', keywords: 'love brown chocolate earth' },
      { emoji: '🖤', name: 'black heart', keywords: 'love black dark goth' },
      { emoji: '🤍', name: 'white heart', keywords: 'love white pure peace' },
      { emoji: '💯', name: 'hundred points', keywords: 'score perfect 100 true facts' },
      { emoji: '💢', name: 'anger symbol', keywords: 'mad angry vein anime' },
      { emoji: '💥', name: 'collision', keywords: 'boom explosion bang pow' },
      { emoji: '💫', name: 'dizzy', keywords: 'star sparkle dizzy magic' },
      { emoji: '💦', name: 'sweat droplets', keywords: 'water drops drip sweat wet' },
      { emoji: '💨', name: 'dashing away', keywords: 'fast zoom wind running puff' },
      { emoji: '🕳️', name: 'hole', keywords: 'dark deep abyss void' },
      { emoji: '💬', name: 'speech balloon', keywords: 'chat message talk bubble' },
      { emoji: '💭', name: 'thought balloon', keywords: 'think dream cloud bubble' },
      { emoji: '💤', name: 'zzz', keywords: 'sleep snoring tired bedtime' },
    ],
  },
  {
    id: 'people',
    name: 'People & Gestures',
    icon: '👋',
    emojis: [
      { emoji: '👋', name: 'waving hand', keywords: 'wave hello goodbye hi bye' },
      { emoji: '🤚', name: 'raised back of hand', keywords: 'hand stop back' },
      { emoji: '🖐️', name: 'hand with fingers splayed', keywords: 'five high five hand' },
      { emoji: '✋', name: 'raised hand', keywords: 'stop high five halt palm' },
      { emoji: '🖖', name: 'vulcan salute', keywords: 'spock trek peace star' },
      { emoji: '👌', name: 'OK hand', keywords: 'perfect okay nice good fine' },
      { emoji: '🤌', name: 'pinched fingers', keywords: 'italian what mama mia' },
      { emoji: '🤏', name: 'pinching hand', keywords: 'small tiny little bit' },
      { emoji: '✌️', name: 'victory hand', keywords: 'peace two v win victory' },
      { emoji: '🤞', name: 'crossed fingers', keywords: 'luck hope wish promise' },
      { emoji: '🤟', name: 'love-you gesture', keywords: 'ily love rock sign' },
      { emoji: '🤘', name: 'sign of the horns', keywords: 'rock metal music cool' },
      { emoji: '🤙', name: 'call me hand', keywords: 'shaka phone hang loose' },
      { emoji: '👈', name: 'backhand index pointing left', keywords: 'point left direction' },
      { emoji: '👉', name: 'backhand index pointing right', keywords: 'point right direction' },
      { emoji: '👆', name: 'backhand index pointing up', keywords: 'point up ceiling above' },
      { emoji: '🖕', name: 'middle finger', keywords: 'rude offensive gesture' },
      { emoji: '👇', name: 'backhand index pointing down', keywords: 'point down bottom below' },
      { emoji: '☝️', name: 'index pointing up', keywords: 'one point up attention note' },
      { emoji: '👍', name: 'thumbs up', keywords: 'like approve good yes agree ok' },
      { emoji: '👎', name: 'thumbs down', keywords: 'dislike bad no disagree reject' },
      { emoji: '✊', name: 'raised fist', keywords: 'power punch strength solidarity' },
      { emoji: '👊', name: 'oncoming fist', keywords: 'punch bro fist bump attack' },
      { emoji: '🤛', name: 'left-facing fist', keywords: 'fist bump punch' },
      { emoji: '🤜', name: 'right-facing fist', keywords: 'fist bump punch' },
      { emoji: '👏', name: 'clapping hands', keywords: 'clap applause bravo kudos cheer' },
      { emoji: '🙌', name: 'raising hands', keywords: 'hooray celebrate praise hallelujah' },
      { emoji: '👐', name: 'open hands', keywords: 'hands open embrace welcome' },
      { emoji: '🤲', name: 'palms up together', keywords: 'prayer hold open book' },
      { emoji: '🤝', name: 'handshake', keywords: 'deal agreement partner shake' },
      { emoji: '🙏', name: 'folded hands', keywords: 'pray please thank you namaste bless' },
      { emoji: '✍️', name: 'writing hand', keywords: 'write pen write notes draw' },
      { emoji: '💅', name: 'nail polish', keywords: 'beauty manicure care slay stylish' },
      { emoji: '🤳', name: 'selfie', keywords: 'camera phone photo pose' },
      { emoji: '💪', name: 'flexed biceps', keywords: 'strong muscle power fitness arm' },
      { emoji: '🦾', name: 'mechanical arm', keywords: 'bionic robot cyborg prosthetics' },
      { emoji: '🧠', name: 'brain', keywords: 'smart intellect mind think thought' },
      { emoji: '👀', name: 'eyes', keywords: 'look see watch look at sneak peek' },
      { emoji: '👁️', name: 'eye', keywords: 'vision watch gaze look' },
      { emoji: '👅', name: 'tongue', keywords: 'taste mouth lick' },
      { emoji: '👄', name: 'mouth', keywords: 'lips kiss speak speech red' },
      { emoji: '👶', name: 'baby', keywords: 'child infant young newborn' },
      { emoji: '🧒', name: 'child', keywords: 'kid youth young' },
      { emoji: '👦', name: 'boy', keywords: 'guy male young son' },
      { emoji: '👧', name: 'girl', keywords: 'female young daughter' },
      { emoji: '🧑', name: 'person', keywords: 'human adult individual' },
      { emoji: '👱', name: 'person: blond hair', keywords: 'blond blonde hair' },
      { emoji: '👨', name: 'man', keywords: 'male adult guy' },
      { emoji: '🧔', name: 'person: beard', keywords: 'beard facial hair man' },
      { emoji: '👩', name: 'woman', keywords: 'female adult lady' },
      { emoji: '🧓', name: 'older person', keywords: 'elder senior elderly' },
      { emoji: '👴', name: 'old man', keywords: 'grandfather senior grandpa' },
      { emoji: '👵', name: 'old woman', keywords: 'grandmother senior grandma' },
      { emoji: '🫡', name: 'saluting face', keywords: 'salute respect yes sir captain' },
    ],
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: '🐻',
    emojis: [
      { emoji: '🐶', name: 'dog face', keywords: 'dog puppy pet canine' },
      { emoji: '🐱', name: 'cat face', keywords: 'cat kitty feline pet' },
      { emoji: '🐭', name: 'mouse face', keywords: 'mouse rodent squeak' },
      { emoji: '🐹', name: 'hamster', keywords: 'hamster cute pet rodent' },
      { emoji: '🐰', name: 'rabbit face', keywords: 'bunny rabbit pet cute' },
      { emoji: '🦊', name: 'fox', keywords: 'fox cunning wild animal' },
      { emoji: '🐻', name: 'bear', keywords: 'bear grizzly wild nature' },
      { emoji: '🐼', name: 'panda', keywords: 'panda bear bamboo cute' },
      { emoji: '🐨', name: 'koala', keywords: 'koala australia animal cute' },
      { emoji: '🐯', name: 'tiger face', keywords: 'tiger cat wild predator' },
      { emoji: '🦁', name: 'lion', keywords: 'lion king roar wild mane' },
      { emoji: '🐮', name: 'cow face', keywords: 'cow milk beef farm moo' },
      { emoji: '🐷', name: 'pig face', keywords: 'pig farm pork oink' },
      { emoji: '🐸', name: 'frog', keywords: 'frog toad amphibian ribbit' },
      { emoji: '🐵', name: 'monkey face', keywords: 'monkey ape jungle animal' },
      { emoji: '🙈', name: 'see-no-evil monkey', keywords: 'monkey see eyes cover blind' },
      { emoji: '🙉', name: 'hear-no-evil monkey', keywords: 'monkey hear ears cover deaf' },
      { emoji: '🙊', name: 'speak-no-evil monkey', keywords: 'monkey speak mouth cover silent' },
      { emoji: '🐔', name: 'chicken', keywords: 'chicken bird farm poultry' },
      { emoji: '🐧', name: 'penguin', keywords: 'penguin bird antarctica cold' },
      { emoji: '🐦', name: 'bird', keywords: 'bird fly tweet chirp' },
      { emoji: '🐤', name: 'baby chick', keywords: 'chick bird young cute' },
      { emoji: '🦆', name: 'duck', keywords: 'duck quack pond waterfowl' },
      { emoji: '🦅', name: 'eagle', keywords: 'eagle bird prey raptor freedom' },
      { emoji: '🦉', name: 'owl', keywords: 'owl bird night wisdom hoot' },
      { emoji: '🦇', name: 'bat', keywords: 'bat vampire nocturnal cave night' },
      { emoji: '🐺', name: 'wolf', keywords: 'wolf pack howl wild canine' },
      { emoji: '🐗', name: 'boar', keywords: 'boar wild pig animal' },
      { emoji: '🐴', name: 'horse face', keywords: 'horse farm stallion pony' },
      { emoji: '🦄', name: 'unicorn', keywords: 'unicorn magic horn fantasy rainbow' },
      { emoji: '🐝', name: 'honeybee', keywords: 'bee honey insect sting buzz' },
      { emoji: '🐛', name: 'bug', keywords: 'caterpillar insect green code bug' },
      { emoji: '🦋', name: 'butterfly', keywords: 'butterfly insect pretty wings' },
      { emoji: '🐌', name: 'snail', keywords: 'snail slow shell garden' },
      { emoji: '🐞', name: 'lady beetle', keywords: 'ladybug bug beetle red spots' },
      { emoji: '🐜', name: 'ant', keywords: 'ant insect colony worker' },
      { emoji: '🕷️', name: 'spider', keywords: 'spider web arachnid spooky' },
      { emoji: '🐢', name: 'turtle', keywords: 'turtle tortoise slow reptile shell' },
      { emoji: '🐍', name: 'snake', keywords: 'snake reptile python hiss venom' },
      { emoji: '🦎', name: 'lizard', keywords: 'lizard gecko reptile wild' },
      { emoji: '🐙', name: 'octopus', keywords: 'octopus sea ocean tentacles' },
      { emoji: '🦑', name: 'squid', keywords: 'squid sea calamari ocean' },
      { emoji: '🦐', name: 'shrimp', keywords: 'shrimp seafood prawn small' },
      { emoji: '🦀', name: 'crab', keywords: 'crab claws seafood ocean beach' },
      { emoji: '🐡', name: 'blowfish', keywords: 'pufferfish fish ocean spikes' },
      { emoji: '🐠', name: 'tropical fish', keywords: 'fish ocean sea reef aquarium' },
      { emoji: '🐟', name: 'fish', keywords: 'fish swim lake river seafood' },
      { emoji: '🐬', name: 'dolphin', keywords: 'dolphin marine ocean mammal smart' },
      { emoji: '🐳', name: 'spouting whale', keywords: 'whale ocean sea blowhole giant' },
      { emoji: '🦈', name: 'shark', keywords: 'shark predator jaws ocean' },
      { emoji: '🌲', name: 'evergreen tree', keywords: 'tree pine forest nature wood' },
      { emoji: '🌳', name: 'deciduous tree', keywords: 'tree nature green shade park' },
      { emoji: '🌴', name: 'palm tree', keywords: 'palm tropical beach island summer' },
      { emoji: '🌱', name: 'seedling', keywords: 'plant sprout growth start young' },
      { emoji: '🌿', name: 'herb', keywords: 'herb leaf plant green nature' },
      { emoji: '🍀', name: 'four leaf clover', keywords: 'luck clover irish st patrick' },
      { emoji: '🍁', name: 'maple leaf', keywords: 'leaf autumn fall canada foliage' },
      { emoji: '🍄', name: 'mushroom', keywords: 'fungus toadstool nature forest mario' },
      { emoji: '💐', name: 'bouquet', keywords: 'flowers gift wedding celebration' },
      { emoji: '🌸', name: 'cherry blossom', keywords: 'flower blossom sakura pink spring' },
      { emoji: '🌹', name: 'rose', keywords: 'flower red romance love valentines' },
      { emoji: '🌻', name: 'sunflower', keywords: 'flower sun yellow summer tall' },
      { emoji: '⭐', name: 'star', keywords: 'star night sky yellow favorite' },
      { emoji: '🌟', name: 'glowing star', keywords: 'star sparkle shine magic shine' },
      { emoji: '✨', name: 'sparkles', keywords: 'sparkle magic glitter clean new shiny' },
      { emoji: '⚡', name: 'high voltage', keywords: 'lightning bolt zap electricity energy power speed' },
      { emoji: '🔥', name: 'fire', keywords: 'fire flame lit hot burn trendy dev' },
      { emoji: '🌈', name: 'rainbow', keywords: 'rainbow colors sky nature rain sun' },
      { emoji: '☀️', name: 'sun', keywords: 'sunny weather bright light day' },
      { emoji: '🌙', name: 'crescent moon', keywords: 'moon night dark evening sleep' },
      { emoji: '🌊', name: 'water wave', keywords: 'wave ocean sea water tsunami surf' },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍔',
    emojis: [
      { emoji: '🍏', name: 'green apple', keywords: 'apple fruit fruit food healthy' },
      { emoji: '🍎', name: 'red apple', keywords: 'apple fruit fruit food sweet' },
      { emoji: '🍌', name: 'banana', keywords: 'banana fruit yellow snack monkey' },
      { emoji: '🍉', name: 'watermelon', keywords: 'watermelon fruit summer picnic melon' },
      { emoji: '🍇', name: 'grapes', keywords: 'grapes fruit wine purple snack' },
      { emoji: '🍓', name: 'strawberry', keywords: 'berry strawberry fruit sweet red' },
      { emoji: '🍒', name: 'cherries', keywords: 'cherry fruit twin red sweet' },
      { emoji: '🍑', name: 'peach', keywords: 'peach fruit butt soft sweet' },
      { emoji: '🥭', name: 'mango', keywords: 'mango fruit tropical sweet' },
      { emoji: '🍍', name: 'pineapple', keywords: 'pineapple fruit tropical hawaii' },
      { emoji: '🥑', name: 'avocado', keywords: 'avocado fruit guacamole healthy keto' },
      { emoji: '🥦', name: 'broccoli', keywords: 'broccoli vegetable green healthy' },
      { emoji: '🌽', name: 'ear of corn', keywords: 'corn vegetable maize farm cob' },
      { emoji: '🌶️', name: 'hot pepper', keywords: 'chili spicy hot pepper seasoning' },
      { emoji: '🥐', name: 'croissant', keywords: 'croissant bakery pastry french breakfast' },
      { emoji: '🍞', name: 'bread', keywords: 'loaf bread wheat toast bakery' },
      { emoji: '🧀', name: 'cheese wedge', keywords: 'cheese cheddar dairy snack' },
      { emoji: '🥓', name: 'bacon', keywords: 'bacon meat breakfast pork crispy' },
      { emoji: '🍔', name: 'hamburger', keywords: 'burger fast food beef sandwich meal' },
      { emoji: '🍟', name: 'french fries', keywords: 'fries fast food potato chips salty' },
      { emoji: '🍕', name: 'pizza', keywords: 'pizza slice cheese pepperoni italian' },
      { emoji: '🌭', name: 'hot dog', keywords: 'hotdog sausage bun stadium' },
      { emoji: '🥪', name: 'sandwich', keywords: 'sandwich lunch bread deli food' },
      { emoji: '🌮', name: 'taco', keywords: 'taco mexican food shell fiesta' },
      { emoji: '🌯', name: 'burrito', keywords: 'burrito wrap mexican food roll' },
      { emoji: '🍜', name: 'steaming bowl', keywords: 'ramen noodles soup asian broth' },
      { emoji: '🍣', name: 'sushi', keywords: 'sushi japanese fish rice sashimi' },
      { emoji: '🍦', name: 'soft ice cream', keywords: 'ice cream dessert sweet cold summer' },
      { emoji: '🍩', name: 'doughnut', keywords: 'donut dessert sweet glazed bakery' },
      { emoji: '🍪', name: 'cookie', keywords: 'cookie chocolate chip sweet bakery' },
      { emoji: '🎂', name: 'birthday cake', keywords: 'cake celebration party candles sweet' },
      { emoji: '🍫', name: 'chocolate bar', keywords: 'chocolate candy sweet dessert cocoa' },
      { emoji: '🍿', name: 'popcorn', keywords: 'popcorn movie cinema snack theater' },
      { emoji: '☕', name: 'hot beverage', keywords: 'coffee tea cafe morning espresso caffeine' },
      { emoji: '🧋', name: 'bubble tea', keywords: 'boba milk tea tapioca drink' },
      { emoji: '🍺', name: 'beer mug', keywords: 'beer alcohol pub drink cheers pint' },
      { emoji: '🍻', name: 'clinking beer mugs', keywords: 'cheers beers drink celebrate pub' },
      { emoji: '🍷', name: 'wine glass', keywords: 'wine drink red alcohol grape' },
      { emoji: '🍸', name: 'cocktail glass', keywords: 'cocktail martini drink alcohol party' },
      { emoji: '🍾', name: 'bottle with popping cork', keywords: 'champagne celebration celebrate party pop' },
    ],
  },
  {
    id: 'activity',
    name: 'Activity & Sports',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: 'soccer ball', keywords: 'football soccer ball sport game goal' },
      { emoji: '🏀', name: 'basketball', keywords: 'basketball ball sport hoop nba game' },
      { emoji: '🏈', name: 'american football', keywords: 'football nfl ball sport touchdown' },
      { emoji: '⚾', name: 'baseball', keywords: 'baseball ball sport strike out mlb' },
      { emoji: '🎾', name: 'tennis', keywords: 'tennis racket ball court sport match' },
      { emoji: '🏐', name: 'volleyball', keywords: 'volleyball beach ball sport bump' },
      { emoji: '🎱', name: 'pool 8 ball', keywords: 'billiards pool eight ball game luck' },
      { emoji: '🏓', name: 'ping pong', keywords: 'table tennis paddle ball game' },
      { emoji: '🏸', name: 'badminton', keywords: 'shuttlecock racket sport game bird' },
      { emoji: '🥊', name: 'boxing glove', keywords: 'boxing glove fight combat punch match' },
      { emoji: '🎯', name: 'bullseye', keywords: 'target bullseye dart goal hit accuracy' },
      { emoji: '🎮', name: 'video game', keywords: 'controller gaming game console play playstation xbox' },
      { emoji: '🕹️', name: 'joystick', keywords: 'joystick arcade retro game play' },
      { emoji: '🎲', name: 'game die', keywords: 'dice roll gamble board game luck' },
      { emoji: '🏆', name: 'trophy', keywords: 'trophy prize win winner champion gold' },
      { emoji: '🥇', name: '1st place medal', keywords: 'gold medal first win winner champion' },
      { emoji: '🥈', name: '2nd place medal', keywords: 'silver medal second runner up' },
      { emoji: '🥉', name: '3rd place medal', keywords: 'bronze medal third place' },
      { emoji: '🎉', name: 'party popper', keywords: 'celebration celebrate party congrats hooray tada' },
      { emoji: '🎊', name: 'confetti ball', keywords: 'confetti celebrate party celebration' },
    ],
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: '🚀',
    emojis: [
      { emoji: '🚗', name: 'automobile', keywords: 'car vehicle drive road travel auto' },
      { emoji: '🚕', name: 'taxi', keywords: 'cab taxi ride yellow uber car' },
      { emoji: '🏎️', name: 'racing car', keywords: 'race f1 fast speed car' },
      { emoji: '🚑', name: 'ambulance', keywords: 'hospital emergency medical siren rescue' },
      { emoji: '🚒', name: 'fire engine', keywords: 'fire truck firefighter emergency siren' },
      { emoji: '🚲', name: 'bicycle', keywords: 'bike cycle ride exercise transport' },
      { emoji: '🛵', name: 'motor scooter', keywords: 'vespa scooter moped delivery ride' },
      { emoji: '✈️', name: 'airplane', keywords: 'plane flight travel airport fly vacation' },
      { emoji: '🛫', name: 'airplane departure', keywords: 'takeoff airport flight travel vacation' },
      { emoji: '🛬', name: 'airplane arrival', keywords: 'landing airport arrive flight vacation' },
      { emoji: '🚀', name: 'rocket', keywords: 'rocket launch space ship blastoff moon to the moon' },
      { emoji: '🛸', name: 'flying saucer', keywords: 'ufo alien space saucer spaceship' },
      { emoji: '🚁', name: 'helicopter', keywords: 'chopper fly air pilot copter' },
      { emoji: '⛵', name: 'sailboat', keywords: 'boat sail ocean sea lake water cruise' },
      { emoji: '🚢', name: 'ship', keywords: 'cruise boat sea ocean voyage titanic' },
      { emoji: '⚓', name: 'anchor', keywords: 'anchor marine navy ship nautical harbor' },
      { emoji: '⛽', name: 'fuel pump', keywords: 'gas petrol station fuel diesel pump' },
      { emoji: '🏖️', name: 'beach with umbrella', keywords: 'beach ocean sand vacation relax resort' },
      { emoji: '🏕️', name: 'camping', keywords: 'tent camp forest outdoor nature hike' },
      { emoji: '🏠', name: 'house', keywords: 'home building residence property room' },
      { emoji: '🏢', name: 'office building', keywords: 'work company corporation enterprise business' },
      { emoji: '🏰', name: 'castle', keywords: 'castle fantasy fortress medieval royal' },
    ],
  },
  {
    id: 'objects',
    name: 'Objects & Tools',
    icon: '💻',
    emojis: [
      { emoji: '💻', name: 'laptop', keywords: 'computer pc mac tech code dev screen laptop' },
      { emoji: '🖥️', name: 'desktop computer', keywords: 'monitor screen pc tech display station' },
      { emoji: '📱', name: 'mobile phone', keywords: 'cell smartphone iphone android call text' },
      { emoji: '⌨️', name: 'keyboard', keywords: 'typing keys code type computer tech' },
      { emoji: '🖱️', name: 'computer mouse', keywords: 'click pointer scroll computer tech' },
      { emoji: '💾', name: 'floppy disk', keywords: 'save storage retro 90s backup' },
      { emoji: '💿', name: 'optical disk', keywords: 'cd dvd disk media drive storage' },
      { emoji: '📷', name: 'camera', keywords: 'photo snapshot picture lens capture' },
      { emoji: '📸', name: 'camera with flash', keywords: 'picture photo flash shutter' },
      { emoji: '📹', name: 'video camera', keywords: 'film recording movie broadcast cam' },
      { emoji: '🎥', name: 'movie camera', keywords: 'cinema hollywood filming director' },
      { emoji: '🔍', name: 'magnifying glass left', keywords: 'search find inspect look zoom' },
      { emoji: '🔎', name: 'magnifying glass right', keywords: 'search find inspect examine discover' },
      { emoji: '💡', name: 'light bulb', keywords: 'idea smart bright innovation electricity solution' },
      { emoji: '🔦', name: 'flashlight', keywords: 'torch light dark beam illuminate' },
      { emoji: '📖', name: 'open book', keywords: 'read novel learn study education library' },
      { emoji: '📚', name: 'books', keywords: 'study education library read school knowledge' },
      { emoji: '📝', name: 'memo', keywords: 'note paper write document draft checklist' },
      { emoji: '📁', name: 'file folder', keywords: 'directory files storage organization' },
      { emoji: '📂', name: 'open file folder', keywords: 'documents directory files devdrop' },
      { emoji: '📄', name: 'page facing up', keywords: 'document file paper text sheet' },
      { emoji: '📦', name: 'package', keywords: 'box delivery shipping parcel mail cardboard' },
      { emoji: '🔒', name: 'locked', keywords: 'security safe privacy protection encrypt' },
      { emoji: '🔓', name: 'unlocked', keywords: 'open access insecure public decrypt' },
      { emoji: '🔑', name: 'key', keywords: 'password secret auth unlock token door' },
      { emoji: '🔨', name: 'hammer', keywords: 'tool build fix craft construction hit' },
      { emoji: '🔧', name: 'wrench', keywords: 'tool fix repair settings mechanic adjust' },
      { emoji: '🛠️', name: 'hammer and wrench', keywords: 'tools build repair settings config dev' },
      { emoji: '⚙️', name: 'gear', keywords: 'settings cog wheel machine preferences options' },
      { emoji: '🧪', name: 'test tube', keywords: 'science lab chemistry test experiment' },
      { emoji: '🔬', name: 'microscope', keywords: 'science lab biology inspect research' },
      { emoji: '📡', name: 'satellite antenna', keywords: 'radar lan wifi signal network communication' },
      { emoji: '🔋', name: 'battery', keywords: 'charge energy power electricity full' },
      { emoji: '🔌', name: 'electric plug', keywords: 'power electricity cord charge socket' },
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols & Flags',
    icon: '🔣',
    emojis: [
      { emoji: '✅', name: 'check mark button', keywords: 'green check pass success approve complete ok' },
      { emoji: '✔️', name: 'check mark', keywords: 'check tick verified true yes' },
      { emoji: '❌', name: 'cross mark', keywords: 'x no false reject cancel error fail' },
      { emoji: '❎', name: 'cross mark button', keywords: 'x red button delete fail cancel' },
      { emoji: '⚠️', name: 'warning', keywords: 'caution alert danger notice hazard' },
      { emoji: '⛔', name: 'no entry', keywords: 'stop forbidden access denied banned' },
      { emoji: '🚫', name: 'prohibited', keywords: 'no banned forbidden not allowed' },
      { emoji: '❓', name: 'question mark', keywords: 'question help unknown why doubt' },
      { emoji: '❗', name: 'exclamation mark', keywords: 'important attention alert notice wow' },
      { emoji: '🔔', name: 'bell', keywords: 'notification alert chime ring alarm' },
      { emoji: '🔕', name: 'bell with slash', keywords: 'mute silent quiet no notifications' },
      { emoji: '🎵', name: 'musical note', keywords: 'music song melody sound audio tune' },
      { emoji: '🎶', name: 'musical notes', keywords: 'music sound audio melody concert' },
      { emoji: '🚩', name: 'triangular flag', keywords: 'red flag warning marker goal' },
      { emoji: '🏁', name: 'chequered flag', keywords: 'finish race winner finish line end' },
      { emoji: '🏳️‍🌈', name: 'rainbow flag', keywords: 'pride lgbt freedom diversity love' },
      { emoji: '🏴‍☠️', name: 'pirate flag', keywords: 'jolly roger skull crossbones pirate ship' },
    ],
  },
];

const RECENT_STORAGE_KEY = 'devdrop_recent_emojis';
const MAX_RECENT = 24;

// Load recent emojis from localStorage
export function getRecentEmojis() {
  if (typeof localStorage === 'undefined') return QUICK_REACTIONS;
  try {
    const raw = localStorage.getItem(RECENT_STORAGE_KEY);
    if (!raw) return QUICK_REACTIONS;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed;
    }
  } catch {
    // Ignore storage parse error
  }
  return QUICK_REACTIONS;
}

// Track used emoji into recent list
export function saveRecentEmoji(emoji) {
  if (!emoji || typeof localStorage === 'undefined') return;
  try {
    const recents = getRecentEmojis().filter((e) => e !== emoji);
    recents.unshift(emoji);
    if (recents.length > MAX_RECENT) {
      recents.length = MAX_RECENT;
    }
    localStorage.setItem(RECENT_STORAGE_KEY, JSON.stringify(recents));
  } catch {
    // Ignore storage save error
  }
}

// Filter emojis across all categories based on query
export function searchEmojis(query) {
  if (!query || !query.trim()) return [];
  const q = query.trim().toLowerCase();

  const results = [];
  const seen = new Set();

  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.emojis) {
      if (seen.has(item.emoji)) continue;
      if (
        item.emoji.includes(q) ||
        item.name.toLowerCase().includes(q) ||
        item.keywords.toLowerCase().includes(q)
      ) {
        seen.add(item.emoji);
        results.push(item);
      }
    }
  }

  return results;
}

// Check if message text is composed exclusively of 1 to 3 emojis
export function getEmojiOnlyInfo(text) {
  if (!text) return { isEmojiOnly: false, count: 0 };
  const trimmed = text.trim();
  if (!trimmed) return { isEmojiOnly: false, count: 0 };

  // Match emoji graphemes including zero-width joiners and variation selectors
  const emojiRegex = /(\p{Extended_Pictographic}(?:\uFE0F|\u200D\p{Extended_Pictographic})*)/gu;
  const matches = trimmed.match(emojiRegex);
  if (!matches) return { isEmojiOnly: false, count: 0 };

  // Remove matched emojis and any whitespace
  const nonEmoji = trimmed.replace(emojiRegex, '').replace(/\s+/g, '');
  if (nonEmoji.length > 0) {
    return { isEmojiOnly: false, count: 0 };
  }

  return {
    isEmojiOnly: matches.length >= 1 && matches.length <= 3,
    count: matches.length,
  };
}
